website/views.py
from flask_login import login_required, current_user
from .models import Pendings, Person, Form_1, Item, Last, User, Cvs
from . import ALLOWED_EXTENSIONS, db, UPLOAD_FOLDER
from flask import render_template, request, redirect, url_for, flash, Blueprint, send_from_directory
from datetime import date
from werkzeug.utils import secure_filename
import os

# IMPORTANT
# change the path in __init__, UPLOAD_FOLDER

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    query = Person.query.join(Last, Person.id == Last.person_id)\
        .add_columns(Person.id, Person.first_name, Person.last_name, Person.uniqueID, Last.date)
    return render_template("index.html", query=query, user=current_user)


@views.route('/addperson', methods=['POST'])
@login_required
def addperson():

    if request.method == 'POST':
        fname = request.form['fname']
        lname = request.form['lname']
        uniqueID = request.form['uniqueID']

        new_person = Person.query.filter_by(uniqueID=uniqueID).first()
        if new_person:
            flash('Person already loaded', 'error')
        else:
            new_person = Person(first_name=fname, last_name=lname, uniqueID=uniqueID)
            db.session.add(new_person)
            db.session.commit()
            person = Person.query.filter_by(uniqueID=uniqueID).first()
            # person = person.query.order_by(person.id.desc()).first()
            today = date.today()
            todaydate = today.strftime("%Y-%m-%d")
            new_last = Last(person_id=person.id, date=todaydate)
            db.session.add(new_last)
            db.session.commit()
            flash('Person Added!', 'success')
            return redirect(url_for('views.home'))
    return redirect(url_for('views.home'))


# not curretly in use
@views.route('/page_1', methods=['POST'])
@login_required
def page_1():
    if request.method == 'POST':
        person_id = person.query.order_by(person.id.desc()).first()
        person_id = person_id.id
        nacionality = request.form['nacionality']
        address = request.form['address']
        b_day = request.form['b_day']
        civil_status = request.form['civil_status']
        education = request.form['education']
        profession = request.form['profession']
        new_person_form_1 = Form_1(nationality=nationality, address=address,
                                      b_day=fecha_nac, civil_status=civil_status,
                                      education=education, profession=profession, person_id=person_id)
        db.session.add(new_person_form_1)
        db.session.commit()
        return render_template("index.html", user=current_user)



@views.route('/person/<id>', methods=['POST', 'GET'])
@login_required
def indice(id):
    person = Person.query.filter_by(id=id).first()
    page_1 = Form_1.query.filter_by(person_id=id).first()
    return render_template('person.html', person=person, page_1=page_1, user=current_user)


@views.route('/items/<id>', methods=['POST', 'GET'])
@login_required
def items(id):
    person = Person.query.filter_by(id=id).first()
    items = Item.query.filter_by(person_id=id)
    return render_template('items.html', person=person, query=items, id=id, user=current_user)


@views.route('/add_item/<id>', methods=['POST', 'GET'])
@login_required
def additem(id):
    person = Person.query.filter_by(id=id).first()
    item = Item.query.filter_by(person_id=id)
    if request.method == 'POST':
        item = request.form['items']
        assistant = request.form['assistant']
        date = request.form['date']
        new_item = Item(person_id=id, items=item, assistant=assistant, date=date)
        lastTime = Last.query.filter_by(person_id=id).first()
        if lastTime:
            update_date = Last.query.filter_by(person_id=id).update(dict(date=date))
        else:
            lastTime = Last(person_id=id, date=date)
            db.session.add(lastTime)
        db.session.add(new_item)
        db.session.commit()
        return redirect('/items/' + str(person.id))
    return redirect(url_for('views.home'))


@views.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def get_person(id):
    # load all personl data from person
    person = Person.query.filter_by(id=id).first()
    page_1 = Form_1.query.filter_by(person_id=id).first()
    return render_template('edit.html', person=person, page_1=page_1, user=current_user)


@views.route('/update/<id>', methods=['POST'])
@login_required
def update_person(id):
    if request.method == 'POST':

        fname = request.form['name']
        lname = request.form['last_name']
        uniqueID = request.form['uniqueID']

        nationality = request.form['nationality']
        address = request.form['address']
        b_day = request.form['b_day']
        civil_status = request.form['civil_status']
        education = request.form['education']
        profession = request.form['profession']

        update_page_1 = Form_1.query.filter_by(person_id=id).first()

        if update_page_1:
            update_person = Person.query.filter_by(id=id).update(dict(first_name=fname, last_name=lname, uniqueID=uniqueID))
            person_id = id
            nationality = request.form['nationality']
            address = request.form['address']
            b_day = request.form['b_day']
            civil_status = request.form['civil_status']
            education = request.form['education']
            profession = request.form['profession']

            update_page_1 = Form_1.query.filter_by(person_id=id).update(dict(nationality=nationality,
                                                                                address=address, b_day=b_day,
                                                                                civil_status=civil_status,
                                                                                education=education,
                                                                                profession=profession))

            db.session.commit()

            flash('Actualizado!')

        else:
            update_person = Person.query.filter_by(id=id).update(dict(first_name=fname, last_name=lname, uniqueID=uniqueID))
            person_id = id
            nationality = request.form['nationality']
            address = request.form['address']
            b_day = request.form['b_day']
            civil_status = request.form['civil_status']
            education = request.form['education']
            profession = request.form['profession']


            new_person_form_1 = Form_1(nationality=nationality, address=address,
                                          b_day=b_day, civil_status=civil_status,
                                          education=education, profession=profession, person_id=person_id)


            db.session.add(new_person_form_1)
            db.session.commit()
            flash('Updated!')

        return redirect(url_for('views.home'))


@views.route('/delete/<id>', methods=['POST', 'GET'])
@login_required
def delete_person(id):
    delete = Person.query.filter_by(id=id).delete()
    page_1 = Form_1.query.filter_by(person_id=id).delete()
    item = Item.query.filter_by(person_id=id).delete()
    last = Last.query.filter_by(person_id=id).delete()
    db.session.commit()
    flash('Deleted')
    return redirect(url_for('views.home'))


@views.route('/delete/item/<item_id>', methods=['POST', 'GET'])
@login_required
def delete_item(item_id):
    item = Item.query.filter_by(id=item_id).first()
    id = item.person_id
    delete = Item.query.filter_by(id=item_id).delete()
    db.session.commit()
    flash('Deleted')
    return redirect('/items/' + str(id))


@views.route('/admin', methods=['POST', 'GET'])
@login_required
def admin():
    if current_user.id != 1:
        return render_template("unathorized.html")
    else:
        users = User.query.all()
        pending = Pendings.query.all()
        return render_template("admin.html", users=users, pending=pending)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/job/<id>', methods=['POST', 'GET'])
@login_required
def job(id):
    
    list = os.scandir(UPLOAD_FOLDER)
    archivos = []
    
    person = Person.query.filter_by(id=id).first()

    loaded_cvs = Cvs.query.filter_by(person_id=id)

    for archivo in list:
        archivos.append(archivo.name)


    if request.method == 'POST':
        file = request.files['file']
        if file.filename == '':
            flash('No file selected!')
            return redirect('/job/' + str(id))
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)

            for index, archivo in enumerate(archivos):
                if os.path.isfile(UPLOAD_FOLDER + '/' + filename):
                    name = filename.split('.')
                    name2 = name[0]
                    name2 = name2.split('(')
                    filename = name2[0] + '(' + str(index) + ').' + name[1]     
            
            file.save(os.path.join(UPLOAD_FOLDER, filename))
            person = Person.query.filter_by(id=id).first()
            name = filename
            today_date = date.today()
            cv = Cvs(name=name, date=today_date, person_id=id)
            db.session.add(cv)
            db.session.commit()

            return render_template('job.html', id=id, loaded=loaded_cvs, person=person)
    return render_template('job.html', id=id, loaded=loaded_cvs, person=person)


@views.route('/delete/job/<cv_id>', methods=['POST', 'GET'])
@login_required
def delete_cv(cv_id):
    cv = Cvs.query.filter_by(id=cv_id).first()
    if os.path.exists(UPLOAD_FOLDER + '/' + cv.name):
        os.remove(UPLOAD_FOLDER + '/' + cv.name)
        flash('Cv deleted!')
    else:
        flash('Cv already deleted')
    
    id = cv.person_id

website/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>

    <link rel="stylesheet" href="../static/main.css">
    <link rel="shortcut icon" href="#" type="image/x-icon">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
        id="bootstrap-css">

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


</head>

<body class="main-body">
    <header class="navi">
        <a href="/"><img class="nav-img" src="#" alt=""></a>
        <div>
            <ul>
                <li>
                    <a class="nav-button" href="/">Home</a>
                    <a class="nav-button" href="/logout">Logout</a>
                </li>
            </ul>
        </div>
    </header>

    <main class="admin">
        <div class="table-admin1">
            <table id="admin1" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Email</td>
                        <td>Name</td>
                        <td width="180">Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.email}}</td>
                        <td>{{user.first_name}}</td>
                        <td class="td-size">
                            {% if user.id != 1 %}
                            <button class="btn-eliminar">
                                <a href="/deleteuser/{{user.id}}">Delete</a>
                            </button>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="table-admin2">
            <table id="admin2" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Email</td>
                        <td>Name</td>
                        <td width="180">Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for pendings in pending %}
                    <tr>
                        <td>{{pendings.id}}</td>
                        <td>{{pendings.email}}</td>
                        <td>{{pendings.first_name}}</td>
                        <td class="td-size">
                            <button>
                                <a class="btn-authorize" href="/authuser/{{pendings.id}}">Authorize</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

    <footer class="footer">
        <a class="footer-button" href="#">
            <p></p>
        </a>
    </footer>

    <script>
        

        const btnDelete = document.querySelectorAll('.btn-delete');
        if (btnDelete) {
            const btnArray = Array.from(btnDelete);
            btnArray.forEach((btn) => {
                btn.addEventListener('click', (e) => {
                    if (!confirm('Are you sure you want to delete it?')) {
                        e.preventDefault();
                    }
                });
            })
        }

        $(document).ready(function () {
            $('#admin1').DataTable({
                "aLengthMenu": [[3, 5, 8], [3, 5, 8]],
                "pageLength": 5
            }
            );
        });
        $(document).ready(function () {
            $('#admin2').DataTable({
                "aLengthMenu": [[3, 5, 8], [3, 5, 8]],
                "pageLength": 5
            }
            );
        });

    </script>
</body>

</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon">
      </span>
    </button>
    <div class="navbar-collapse collapse" id="navbar">
      <!--<ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="/logout" class="nav-link">Logout</a></li>
                    {% endif %}
                </ul>-->
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="SignUp" href="/sign-up">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container pt-4">
    {% block content %}
    {% endblock %}
  </div>

  <script>
    const btnDelete = document.querySelectorAll('.btn-delete');
    if (btnDelete) {
      const btnArray = Array.from(btnDelete);
      btnArray.forEach((btn) => {
        btn.addEventListener('click', (e) => {
          if (!confirm('Are you sure you want to delete it?')) {
            e.preventDefault();
          }
        });
      })
    }

    $(document).ready(function () {
      $('#example').DataTable({
        "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
      }
      );
    });

  </script>
</body>

</html>

website/templates/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job</title>

    <link rel="stylesheet" href="../static/main.css">
    <link rel="shortcut icon" href="#" type="image/x-icon">
    <script src="https://kit.fontawesome.com/28aaae96af.js" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
        id="bootstrap-css">

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

</head>

<body class="main-body">
    <header class="navi">
        <a href="/"><img class="nav-img" src="#" alt=""></a>
    </header>

    <main class="job">
        <div class="table-job">
            <table id="job" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Date</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for cv in loaded %}
                    <tr>
                        <td width="400px">{{cv.name}}</td>
                        <td width="150px">{{cv.date}}</td>
                        <td width="60">
                            <button>
                                <a href="/download/{{cv.name}}" class="btn-edit" target="_blank">Download</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

    <footer class="footer">
        <a class="footer-button" href="#"><p></p></a>
    </footer>
    

    <script>
        
        $(document).ready(function () {
            $('#empleo').DataTable({
                "aLengthMenu": [[3, 5, 8], [3, 5, 8]],
                "pageLength": 5
            }
            );
        });
    </script>
</body>
</html>

website/templates/edit.html
{% extends "base.html" %}
{% block content %}

    <div class="card card-body">
      <form action="/update/{{person.id}}" method="POST">

        <div class="form-group">
          <label for="nombre">Name</label>
          <input id="name" type="text" name="name" value="{{person.first_name}}" class="form-control" required/>
        </div>

        <div class="form-group">
          <label for="last_name">Last name</label>
          <input id="last_name" type="text" name="last_name" value="{{person.last_name}}" class="form-control" required/>
        </div>

        <div class="form-group">
          <label for="uniqueID">uniqueID</label>
          <input id="uniqueID" type="text" name="uniqueID" value="{{person.uniqueID}}" class="form-control" required/>
        </div>


        <div class="form-group">
          <label for="nationality">nationality</label>
            <input id="nationality" type="text" class="form-control" name="nationality" value="{{page_1.nationality}}">
          </div>

          <div class="form-group">
            <label for="address">address</label>
            <input id="address" type="text" class="form-control" name="address" value="{{page_1.address}}">
          </div>

          <div class="form-group">
            <label for="b_day">Date of Birth</label>
            <input id="b_day" type="date" class="form-control" name="b_day" value="{{page_1.b_day}}">
          </div>

          <div class="form-group">
            <label for="civil_status">Civil Status</label>
            <input id="civil_status" type="text" class="form-control" name="civil_status" value="{{page_1.civil_status}}">
          </div>

          <div class="form-group">
            <label for="education">Education</label>
            <input id="education" type="text" class="form-control" name="education" value="{{page_1.education}}">
          </div>

          <div class="form-group">
            <label for="profession">Profession</label>
            <textarea id="profession" name="profession" class="form-control" >{{page_1.profession}}</textarea>
          </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Update
          </button>
        </div>
      </form>
    </div>

{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Title</title>

  <link rel="stylesheet" href="../static/main.css">
  <link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">

  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


</head>

<body class="main-body">
  <header class="navi">
    <a href="/"><img class="nav-img" src="#" alt=""></a>
    <div>
      <ul>
        <li>

          <a class="nav-button" href="/">Home</a>
          {% if current_user.id == 1 %}
          <a class="nav-button" href="/admin">Admin Panel</a>
          {% endif %}
          <a class="nav-button" href="/logout">Logout</a>
        </li>
      </ul>
    </div>
  </header>

  <main class="index">
    <div class="form">
      <form class="form-index" action="{{url_for('views.addperson')}}" method="POST">
        <h3>Add person</h3>
        <p>Name</p>
        <input type="text" name="fname" autocomplete="off" required>
        <p>Last name</p>
        <input type="text" name="lname" autocomplete="off" required>
        <p>uniqueID</p>
        <input type="text" name="uniqueID" autocomplete="off" required>
        <button>
          Next
        </button>
      </form>
      {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for categories, message in messages %}
            <div class="{{ categories }}">
                {{ message }}
                <button class="closebtn">
                    <i class="close icon" onclick=delete_flash(this)>x</i>
                </button>
            </div>
            {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}
    </div>
    <div class="table-index">
      <table id="index" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Last name</td>
            <td>uniqueID</td>
            <td width="150">Last time</td>
            <td width="180">Action</td>
          </tr>
        </thead>
        <tbody>
          {% for person in query %}
          <tr>
            <td>{{person.id}}</td>
            <td>{{person.first_name}}</td>
            <td>{{person.last_name}}</td>
            <td>{{person.uniqueID}}</td>
            <td>{{person.date}}</td>
            <td class="td-size">
              <button>
                <a href="/person/{{person.id}}" class="btn-edit" target="_blank">Edit</a>
              </button>
              {% if current_user.id == 1 %}
              <button>
                <a href="/delete/{{person.id}}" class="btn-delete btn-eliminar">Delete</a>
              </button>
              {% endif %}

            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>

  <footer class="footer">
    <a class="footer-button" href="#">
      <p></p>
    </a>
  </footer>

  <script>
    const btnDelete = document.querySelectorAll('.btn-delete');
    if (btnDelete) {
      const btnArray = Array.from(btnDelete);
      btnArray.forEach((btn) => {
        btn.addEventListener('click', (e) => {
          if (!confirm('Are you sure you want to delete it?')) {
            e.preventDefault();
          }
        });
      })
    }

    $(document).ready(function () {
      $('#index').DataTable({
        "aLengthMenu": [[3, 5, 8], [3, 5, 8]],
        pagingType: 'simple',
        "pageLength": 5
      }
      );
    });

    function delete_flash(flash) {
            $(flash).parent().parent().remove()
        }
  </script>
</body>

</html>

website/templates/items.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{person.first_name}} {{person.last_name}}</title>

    <link rel="stylesheet" href="../static/main.css">
    <link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">

  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>


</head>

<body class="main-body">
    <header class="navi">
        <a href="/"><img class="nav-img" src="#" alt=""></a>
        <div>
            <ul>
                <li>
                    <a class="nav-button" href="/">Home</a>
                    <a class="nav-button" href="/logout">Logout</a>
                </li>
            </ul>
        </div>
    </header>

    <main class="item">
        <div class="form">
            <form class="form-item" action="/add_item/{{person.id}}" method="POST">
                <h3>Add items</h3>
                <h5>{{person.first_name}} {{person.last_name}}</h5>
                <textarea class="text-area" rows="3" name="items" placeholder="Item" autocomplete="off" required></textarea>
                <input class="input-area" type="text" name="assistant" placeholder="Assistant" autocomplete="off" required>
                <input class="input-area" type="date" name="date" required>
                <button>
                    Add
                </button>
            </form>
        </div>
        <div class="table-item">
            <table id="item" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Date</td>
                        <td>Item</td>
                        <td>Assistant</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for item in query %}
                    <tr>
                        <td width="80">{{item.id}}</td>
                        <td width="130">{{item.date}}</td>
                        <td width="400">{{item.items}}</td>
                        <td width="150">{{item.assistant}}</td>
                        <td width="180">
                            <button>
                                <a href="" class="btn-edit popup" onclick="updatePopUp()">Edit</a>
                            </button>
                            <button>
                                <a href="/delete/item/{{item.id}}" class="btn-delete btn-eliminar">Delete</a>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

    <footer class="footer">
        <a class="footer-button" href="#">
            <p></p>
        </a>
    </footer>

    <script>
        const btnDelete = document.querySelectorAll('.btn-delete');
        if (btnDelete) {
            const btnArray = Array.from(btnDelete);
            btnArray.forEach((btn) => {
                btn.addEventListener('click', (e) => {
                    if (!confirm('Are you sure you want to delete it?')) {
                        e.preventDefault();
                    }
                });
            })
        }

        $(document).ready(function () {
            $('#ropero').DataTable({
                "aLengthMenu": [[3, 5, 10], [3, 5, 10]],
                order: [[0, 'desc']],
                pagingType: 'simple',
                "pageLength": 10
            }
            );
        });

        function updatePopUp(){
            var popup = document.getElementById("myPopup");
            popup.classList.toggle("Show");
        }

    </script>
</body>

</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" href="../static/main.css">
    <link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon">


</head>

<body class="main-body">
    <header class="navi">
        <a href="/"><img class="nav-img" src="#" alt=""></a>
        <div>
            <ul>
                <li>
                    <a class="nav-button" href="/">Home</a>
                    <a class="nav-button" href="/sign-up">Register</a>
                </li>
            </ul>
        </div>

    </header>

    <main class="login">
        <div class="centered">
            <form method="POST">
                <h1 align-item="center">Log In</h1>
                <p>Email</p>
                <input type="email" id="email" name="email" required>
                <p>Password</p>
                <input type="password" id="password" name="password" required>
                <button type="submit">Log In</button>
            </form>
            <div>
                <p>Don't have an account? <a class="register" href="/sign-up">Register</a></p>

            </div>
            <div class="forgot-pass">

                <a href="#">Forgot password?</a>
            </div>
        </div>

    </main>

    <footer class="footer">
        <a class="footer-button" href="#">
            <p></p>
        </a>
    </footer>
</body>

</html>